### ISSUE TITLE
Documentation using Mkdocs

### ISSUE THREAD

**Issue by annmary-roy** [HewlettPackard/cmf#10]

**Comment by sergey-serebryakov** [comment]
Work in progress, see PR #24.

**Comment by sergey-serebryakov** [comment]
The new GitHub [deploy_docs_to_gh_pages.yaml](https://github.com/HewlettPackard/cmf/blob/master/.github/workflows/deploy_docs_to_gh_pages.yaml) workflow automatically builds and deploys the CMF documentation to GitHub pages. It's available at this URL: [https://hewlettpackard.github.io/cmf/](https://hewlettpackard.github.io/cmf/).
